use std::str::FromStr;

grammar;

pub Expr = (Stmt ";")* <Stmt> ";"?;
Stmt = (App "=")* <App>;

Column = (Row ";")* <Row> ";"?;
Row = (App ",")* <App>;

Obj = (Entry ";")* <Entry> ";"?;
Entry = App ":" <App>;

App = Func* <Func>;

Func = (Term ".")* <Term>;

Term = {
    Num,
    Ident,
    "(" <Expr> ")",
    "[" <Column> "]",
    "{" <Obj> "}",
};

Ident = r"[_a-zA-Z][_a-zA-Z0-9]*";

Num = r"[0-9]+";